version: "3.8"
services:
  dev-db:
    restart: always
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: meets_nest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234